name: Chores

on:
  push:
    branches:
      - master
      - main
  pull_request:

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - name: format code
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - run: go fmt .
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "chore(gh_action): : go fmt"
          branch: ${{ github.head_ref }}
